# Generated by Django 4.2.1 on 2023-06-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipient', '0005_initial'),
        ('Guest', '0005_tbl_donar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_applyrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donar')),
                ('requirements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipient.tbl_requirements')),
            ],
        ),
    ]
