# Generated by Django 4.2.1 on 2023-06-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donar', '0003_tbl_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_appointments',
        ),
    ]
