# Generated by Django 4.2.1 on 2023-06-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_donar'),
        ('Donar', '0004_delete_tbl_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donar')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_recipient')),
            ],
        ),
    ]
