# Generated by Django 4.2.1 on 2023-06-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0010_alter_tbl_events_date'),
        ('Guest', '0005_tbl_donar'),
        ('Donar', '0006_delete_tbl_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_paymentrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donar')),
                ('requirements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipient.tbl_requirements')),
            ],
        ),
    ]
