# Generated by Django 4.2.1 on 2023-05-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('for_date', models.DateField()),
                ('date_of_post', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
