# Generated by Django 4.2.1 on 2023-06-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_tbl_donar'),
        ('Recipient', '0002_delete_tbl_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('for_date', models.DateField()),
                ('date_of_post', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_recipient')),
            ],
        ),
    ]
