# Generated by Django 4.2.1 on 2023-06-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_requirements',
        ),
    ]
