# Generated by Django 4.2.1 on 2023-06-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0006_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
