# Generated by Django 4.2.1 on 2023-06-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_donar'),
        ('Recipient', '0008_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(default=1)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_recipient')),
            ],
        ),
    ]
