# Generated by Django 4.2.1 on 2023-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0009_tbl_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_events',
            name='date',
            field=models.DateField(),
        ),
    ]
