# Generated by Django 4.2.1 on 2023-05-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('proof', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donar_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=50)),
                ('proof', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
