# Generated by Django 4.2.1 on 2023-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_recipient',
            old_name='place_name',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='tbl_recipient',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='tbl_donar',
        ),
    ]
