# Generated by Django 4.2.1 on 2023-05-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0002_rename_place_name_tbl_recipient_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donar_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=50)),
                ('proof', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
